package se.adi.floggit.api;

public enum ResponseType
{
	USER_CREATED,
	USER_UPDATED,
	USER_DELETED,
	
	USER_EMAIL_DUPLICATE,
	USER_NOT_FOUND,
	
	PRODUCT_CREATED,
	PRODUCT_UPDATED,
	PRODUCT_NOT_FOUND,
	PRODUCT_DELETED,
	
	USER_CART_EMPTY,
	USER_CART_UPDATED,

	LOGIN_SUCCESSFUL,
	LOGIN_FAILED,
	
	CATEGORY_CREATED,
	CATEGORY_NOT_CREATED,
	CATEGORY_UPDATED, 
	CATEGORY_NOT_FOUND,
	CATEGORY_DELETED, 
	CATEGORY_ALREADY_IN_DB, 
	
	STAFF_NOT_FOUND,
	
	SERVER_CONNECTION_SUCCESSFUL,
	SERVER_CONNECTION_FAILED
}
