package se.adi.floggit.api;

public enum ResponseType
{
	USER_CREATED,
	USER_NOT_CREATED,
	USER_UPDATED,
	USER_DELETED,
	USER_NOT_DELETED,
	
	USER_EMAIL_DUPLICATE,
	USER_EMAIL_NOT_FOUND,
	
	USER_CART_EMPTY,
	USER_CART_UPDATED,
	USER_CART_NOT_UPDATED,
	
	PRODUCT_NOT_FOUND,
	
	LOGIN_SUCCESSFUL,
	LOGIN_FAILED,
	
	SERVER_CONNECTION_SUCCESSFUL,
	SERVER_CONNECTION_FAILED
}
